import Head from "next/head";
import SectionWithMargin from "../components/SectionWithMargin";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import CreateProfile from "./create-profile";
import { useState, useEffect } from "react";
import Splash from "../components/Splash";
import Header from "../components/Header";
import Signup from "../components/Signup";
import DiamondBg from "../components/UI/DiamondBg";

import { useContext } from "react";
import { UserContext } from "../context/userContext";
import { useRouter } from "next/router";
import { magicClient } from "../lib/magic";

import { raleway } from "../lib/utils";

export default function Home() {
  const user = useContext(UserContext);
  const [splash, setSplash] = useState(true);
  const router = useRouter();

  // Timer for the splash screen
  useEffect(() => {
    const isSplashShown = localStorage.getItem("isSplashShown");

    if (isSplashShown) {
      setSplash(false);
    } else {
      setTimeout(() => {
        setSplash(false);
        localStorage.setItem("isSplashShown", "true");
      }, 3000);
    }

    // ========== logout ==============
    // async function logout() {
    //   await magicClient.user.logout();
    //   user.updateUser(null);
    // }
    // logout();

    // route based on login status
    user.isLoggedIn ? router.push("/dashboard") : router.push("/signup");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${raleway.className} `}>
        {splash ? (
          <Splash />
        ) : (
          <>
            <Header />
            {/* <DiamondBg /> */}
            <Signup />
          </>
        )}
        <ToastContainer style={{ fontSize: 14 }} />
      </main>
    </>
  );
}
